### ISSUE TITLE
ValueError: ('Vocabulary file %s not found.', 'data/squad/vocab.dat

### ISSUE THREAD

**Issue by loveJasmine** [MurtyShikhar/Question-Answering#3]
python  train.py
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    run_func()
  File "train.py", line 34, in run_func
    vocab, rev_vocab = initialize_vocab(vocab_path)
  File "train.py", line 22, in initialize_vocab
    raise ValueError("Vocabulary file %s not found.", vocab_path)
ValueError: ('Vocabulary file %s not found.', 'data/squad/vocab.dat

**Comment by loveJasmine** [comment]
I figure it out 
run

 python qa_data.py

**Comment by LeenaShekhar** [comment]
In case anyone gets stuck while running this code. I followed the following steps:

Data acquisition and preparation

1. python /preprocessing/squad_preprocess.py  
2. python /preprocessing/dwr.py 
3. python qa_data.py [make sure you have squad and dwr under the download folder]
Training
4. python train.py
